# Generated by Django 3.1.3 on 2020-12-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_auto_20201208_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='E:\\DjangoBlog\x07blog\\static\theblog\\images\\default.jpg', null=True, upload_to='images/profile/'),
        ),
    ]
